# Site
repository: sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 강민호
title: 안녕하세요 강민호입니다.
email: boo10500@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  boo105
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Blog
  icon: fas fa-blog
  url: https://velog.io/@boo105
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  **~ 좋은 개발은 읽기 좋은 코드에서 나온다. ~**<br>
  프로그래밍뿐만 아니라 프로젝트를 진행하는 과정에서 협업 방식, 프로젝트 관리 방식 등의 기술들이 매우 중요하다고 생각합니다.
  '코드는 사람이 이해하기 쉽게 읽는 것'이라는 마음가짐으로 클린 코드를 지향합니다.  
  서비스의 품질을 위해서는 TDD가 매우 중요하다고 생각합니다. TDD를 지향하여 최대한 다양한 예외 상황과 버그에 대해 대응하려고 
  테스트 코드에 작성에 대해 노력하고 있습니다.
  프로젝트가 어떤 것이 부족하고 개선해야 되는지 항상 생각하여 발전해 나가고 있습니다.

#  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.
#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
#        title:
        caption: <div class="sticky"> <h4>선인장</h4> <p> 2022.01 ~ 2023.02</p> </div> # 이거 편법임........... 그냥 템플릿 안쓰고 내가 만들걸..
#        link: 일단 비공개?
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          <h4 class="intro-bold"> Description </h4>
          평소에 결정을 잘 못 하는 사람들을 위해 만든 커뮤니티 어플입니다.<br>
          고민거리에 대해 투표를 통하여 사용자의 결정을 도와줍니다.
          <h4 class="intro-bold"> What Did I Do </h4>
          - 커뮤니티 API 구현
          - Exception Handler 구현
          - 사용자 인증 구현
          - 프로젝트 구조 구축
          - 테스트 환경 구축
          - 개발 환경 분리
          - CI/CD 자동화 구축
          <h4 class="intro-bold"> Result </h4>
          <h2 class="small-title">소셜로그인 기능에 대응이 가능한 플랫폼 확장</h2>
          - 기존에는 백엔드에서 인증, 인가, 자원 요청 단계를 모두 처리하였기 때문에 안드로이드에서는 해당 방식 대응이 어렵다
          - 이를 해결하기 위해 클라이언트가 인증/인가의 단계를 수행하도록 Authorization 서버에 요청해 AccessToken 발급 후 백엔드에 요청
          - 백엔드에서 해당 AccessToken을 가지고 Resource 서버에 요청해 사용자 정보를 받아 소셜로그인 구현
          - Resource 서버에 요청해 특정 플랫폼을 위한 소셜로그인 기능을 가진 API 구현
          
          <h2 class="small-title">프로젝트 아키텍처 개선</h2>  
          - 하나의 Service에는 여러 Repository를 가지고 있기 때문에 많은 책임(기능)을 가지고 있음
          - 하나의 Service에는 많은 책임(기능)을 가지고 있어 스파게티 코드가 될 위험이 높았음
          - 하나의 Service에는 하나의 Repository를 가져야한다는 규칙 생성
          - 해당 규칙으로 Service들을 분리시켜 책임(기능)을 분할해 해결
          - 해당 규칙으로 인해 특정 Service에서 타 Service 기능이 필요함에 따라 계층간 구조 개선이 필요
          - Controller에서 특정 Service의 결과를 타 Service로 전달해주는 조합 방식으로 구조를 정의하여 해결
          
          <h4 class="intro-bold"> What Did I Learn </h4>
          - Oauth2 방식
          - 민감 정보 관리
          - 개발 환경 분리
          - 프로젝트 협업 방식
          - MVC 아키텍처 설계

          <h4 class="intro-bold"> TechStack </h4>
          SpringBoot, Java, Kotlin, PostgreSQL, Redis , Docker

      - layout: left
#        title: EasyHost
        caption: <div class="sticky"> <h4> EasyHost </h4> <p>2022.06 ~ 2022.08</p> </div>
          # link_text: Project Website
          #        additional_links:
          #          - title:  sproogen/modern-resume-theme
          #            icon: fab fa-github
          #            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          <h4 class="intro-bold"> Description </h4>
          쉽게 일반 서버, 게임 서버 등의 구축을 위한 VPS 호스팅 서비스입니다.
          <h4 class="intro-bold"> What Did I Do </h4>
          - 토스 페이먼츠를 이용한 결제 시스템 구현
          - 본인인증 시스템 구현
          - VPS 서비스 연동 구현
          - CI/CD 자동화 구축
          - 테스트 환경 구축
          <h4 class="intro-bold"> Result </h4>
          <h2 class="small-title"> 서비스 품질 개선 </h2>
          - 테스트 환경이 갖추어지지 않아 배포 시 빈번한 버그 발생으로 불안정한 서비스로 이어짐 
          - 테스트 환경 구축으로 신뢰성 있는 서비스 제공으로 해결
          
          <h4 class="intro-bold"> What Did I Learn </h4>
          - API 문서의 중요성
          - 테스트 코드의 중요성
          - 다양한 예외처리에 대한 중요성
          
          <h4 class="intro-bold"> TechStack </h4>
          NestJs, TypeScript, Jest, MariaDB, Docker
  
  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Google Developer Student Clubs<br>(GDSC DJU)
        link: https://web.gdsc-dju.com/
        # link_text: boringcompany.com
        sub_title: 1기 Member
        caption: 2022.02 ~ 현재
        description: | # this will include new lines to allow paragraphs
          학생들이 개발 및 협업 능력을 기를 수 있도록
          다양한 프로젝트 및 활동하는 동아리입니다.
          <h4 class="intro-bold"> 동아리 문화 </h4>
          - 모든 활동 내용을 멤버들에게 공유
          - 칭찬 시스템
          - 누구나 활동을 주도할 수 있는 환경
          - 수평적인 문화
          
          <h4 class="intro-bold"> 내가 활동한 것 </h4>
          - 선인장 프로젝트
          - 동아리 슬랙 봇 개발 및 관리
          - 백엔드 스터디
          - 개발 지식 공유

      - layout: left
        title: 지능정보시스템<br>(인공지능) 연구실
        link: https://notion.ai.re.kr/
        sub_title: 랩장
        caption: 2016.08 ~ 2023.02
        description: | 
          인공지능에 대해 다양한 프로젝트와 활동을 진행하는 연구실입니다.
          
          <h4 class="intro-bold"> 연구실 프로젝트의 문제점 </h4>
          - 기존 프로젝트 관리는 구두 혹은 카카오톡으로만 관리가 되었음
          - 이로 인해 회의를 진행해도 프로젝트의 개발 목표가 자주 변경되거나 잊어버리는 문제 발생
          - 따라서 모든 프로젝트 관리 및 협업을 Jira와 스크럼 방식으로 변경하여 해결함
          
          <h4 class="intro-bold"> 참여 프로젝트 </h4>
          - Bllearn 프로젝트 (교내 캡스톤 디자인, 창의적 종합설계 과제 등 수상)
          - 여행고수 프로젝트
          - 2021 항만 물류 인공지능 학습데이터 해커톤 - 최우수상

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      <div class = "content">
      
      <h4 class="intro-bold"> SpringBoot </h4>
      <ul class="skill">
      <li> SpringBoot를 사용해 서비스를 만든 경험을 가지고 있습니다. </li>
      <li> WebMVC, WebFlux, Spring Cloud(MSA) 사용 경험을 가지고 있습니다. </li>
      <li> 테스트 환경을 구축할 수 있습니다. </li>
      </ul>
      
      <h4 class="intro-bold"> Java </h4>
      <ul class="skill">
      <li> Junit를 사용해 단위테스트를 할 수 있습니다. </li>
      <li> 기초적인 Reactive 프로그래밍 사용할 수 있습니다. </li>
      </ul>
      
      <h4 class="intro-bold"> Database </h4>
      <ul class="skill">
      <li> MySQL, PostgreSQL, MongoDB 사용 경험을 가지고 있습니다. </li>
      <li> Redis로 Cache 사용 경험을 가지고 있습니다. </li>
      </ul>
      
      <h4 class="intro-bold"> DevOps </h4>
      <ul class="skill">
      <li> GitHub Actions를 사용해 CI/CD를 자동화 할 수 있습니다. </li>
      <li> Jira, Slack, Notion을 사용하여 프로젝트 관리 경험이 있습니다. </li>
      <li> AWS EC2를 구축하여 서비스 경험이 있습니다. </li>
      </ul>
      </div>

  - title: Education # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      <div class="content">
      <h4 class="intro-bold"> 대진대학교 </h4>
      <p class="education"> 2016.03 ~ 2023.02 </p>
      <p class="education">
      <b> 컴퓨터공학전공 </b>
      </p>
      <p>최종 학점 : 4.31 / 4.5</p>
      </div>

  - title: Certificate # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      <div class="certificate-content">
      <h4 class="intro-bold"> 정보처리기사 </h4>
      <p class="education"> 2022.06 </p>
      </div>
      
      <div class="certificate-content">
      <h4 class="intro-bold"> 정보처리기능사 </h4>
      <p class="education"> 2017.12 </p>
      </div>

  - title: Military Service # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      <div class="content">
      <h4 class="intro-bold"> 육군 포병 만기제대 </h4>
      <p class="education"> 2017.02 ~ 2018.11 </p>
      </div>




# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
